WebUI/Areas/Admin/Controllers/UserController.cs
using Entities.Concreate;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using WebUI.Areas.ViewModels;
using WebUI.Extensions;

namespace WebUI.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]
    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly IFileProvider _fileProvider;
        public UserController(UserManager<User> userManager, SignInManager<User> signInManager, IFileProvider fileProvider)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _fileProvider = fileProvider;
        }
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.FindByNameAsync(User.Identity!.Name!);

            var userViewModel = new UserViewModel
            {
                Email = currentUser!.Email,
                UserName = currentUser.UserName,
                PictureUrl = currentUser.Picture,
                FirstName = currentUser.FirstName,
                LastName = currentUser.LastName,
            };
            return View(userViewModel);
        }


        [HttpGet]
        public IActionResult PasswordChange()
        {
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> PasswordChange(PasswordChangeViewModel request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var currentUser = await _userManager.FindByNameAsync(User.Identity!.Name!);


            var checkOldPassword = await _userManager.CheckPasswordAsync(currentUser, request.PasswordOld);

            if (!checkOldPassword)
            {
                ModelState.AddModelError(string.Empty, "Your old password is wrong!");
                return View();
            }

            var result = await _userManager.ChangePasswordAsync(currentUser, request.PasswordOld, request.PasswordNew);

            if (!result.Succeeded)
            {
                ModelState.AddModelErrorlist(result.Errors);
                return View();
            }


            await _userManager.UpdateSecurityStampAsync(currentUser);
            await _signInManager.SignOutAsync();
            await _signInManager.PasswordSignInAsync(currentUser, request.PasswordNew, true, false);

            TempData["SuccessMessage"] = "Your password has been successfully changed";


            return View();
        }


        [HttpGet]
        public async Task<IActionResult> UserEdit()
        {


            var currentuser = await _userManager.FindByNameAsync(User.Identity!.Name!);

            var userEditViewModel = new UserEditViewModel()
            {
                FirstName = currentuser.FirstName,
                LastName = currentuser.LastName,
                Email = currentuser.Email
            };

            return View(userEditViewModel);
        }



        [HttpPost]
        public async Task<IActionResult> UserEdit(UserEditViewModel request)
        {


            if (!ModelState.IsValid)
            {
                return View();
            }


            var currentUser = await _userManager.FindByNameAsync(User.Identity!.Name!);

            currentUser.FirstName = request.FirstName;
            currentUser.LastName = request.LastName;
            currentUser.Email = request.Email;

            if (request.Picture != null && request.Picture.Length > 0)
            {
                var wwwrootFolder = _fileProvider.GetDirectoryContents("wwwroot");

                var randomFileName = $"{Guid.NewGuid().ToString()}{Path.GetExtension
                    (request.Picture.FileName)}";


                var newPicturePath = Path.Combine(wwwrootFolder.First(x => x.Name == "userPictures")
                    .PhysicalPath!, randomFileName);

                using var stream = new FileStream(newPicturePath, FileMode.Create);

                await request.Picture.CopyToAsync(stream);

                currentUser.Picture = randomFileName;

            }

            var updateToUserResult = await _userManager.UpdateAsync(currentUser);

            if (!updateToUserResult.Succeeded)
            {
                ModelState.AddModelErrorlist(updateToUserResult.Errors);
                return View();
            }

            await _userManager.UpdateSecurityStampAsync(currentUser);
            await _signInManager.SignOutAsync();
            await _signInManager.SignInAsync(currentUser, isPersistent: true);

            TempData["SuccessMessage"] = "Your information has been successfully changed";



            var userEditViewModel = new UserEditViewModel()
            {
                FirstName = currentUser.FirstName,
                LastName = currentUser.LastName,
                Email = currentUser.Email
            };

            return View(userEditViewModel);
        }

    }
}

WebUI/Controllers/ProductController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using WebUI.Services;
using WebUI.ViewModels;
using WebUI.ViewModels2;

namespace WebUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private LanguageService _languageService;
        public ProductController(IProductService productService, ICategoryService categoryService, LanguageService languageService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _languageService = languageService;
        }

        public IActionResult Index(int id, List<int> categoryIds, int page = 1)        
        {
            var currentColture = Thread.CurrentThread.CurrentCulture.Name;
            ViewBag.CurrentPage = page;
            ViewBag.ProductCount = _productService.GetProductCount(3, categoryIds).Data;

            var products = _productService.GetAllFilteredProducts(categoryIds, currentColture, 0, maxPrice: 10000, pageNo: page, take: 3);
            var categories = _categoryService.GetAllFilterCategories(currentColture);
            var productFeatured = _productService.GetProductDetailFeaturedList(id: id, langCode: currentColture);
            ProductFilterVM productFilterVM = new()
            {
                ProductFilters = products.Data,
                CategoryFilters = categories.Data,
                ProductDetailFeatureds = productFeatured.Data,

            };
            return View(productFilterVM);
        }

         

        public IActionResult Detail(int id)
        {
            var currentColture = Thread.CurrentThread.CurrentCulture.Name;
            ViewBag.RecentProducts = _languageService.GetKey("RECENT IS FEATURED PRODUCTS").Value;
            var productDetail = _productService.GetProductBYId(id, currentColture);
            var productFeatured = _productService.GetProductDetailFeaturedList(id: id, langCode: currentColture);
            //var result3 = _categoryService.GetAllCategoriesFeatured("az-Az");
            DetailVM detailVM = new()
            {
                ProductDetail = productDetail.Data,
                ProductDetailFeaturedDTO = productFeatured.Data,
                //CategoryFeaturedDTOs = result3.Data
            };

            if (productDetail.Success)
            {
                return View(detailVM);
                
            }
            return RedirectToAction(nameof(Index), "Home");
        }



        public JsonResult GetDatas(int page, int take, string categoryList, int minPrice, int maxPrice)
        {
            var currentColture = Thread.CurrentThread.CurrentCulture.Name;
            var categories = _categoryService.GetAllFilterCategories(langCode: currentColture);
            var cats = new List<int>();

            if (categoryList == "null")
            {
                cats = categories.Data.Select(x => x.Id).ToList();
            }
            else
            {
                cats = categoryList.Split(",").Select(x => Convert.ToInt32(x)).ToList();
            }

            var result = _productService.GetAllFilteredProducts(cats, langCode: currentColture, 0, maxPrice: 10000, pageNo: page, take: take);
            var productCount = _productService.GetProductCount(take, cats).Data;
            PagenationVM paginationVM = new()
            {
                ProductCount = productCount,
                Products = result.Data
            };
            return Json(paginationVM);
        }
    }
}

WebUI/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<meta name="description" content="" />
	<meta name="author" content="" />
	<title>Dashtreme Admin - Free Dashboard for Bootstrap 4 by Codervent</title>
	<!-- loader-->
	<link href="~/Auth/css/pace.min.css" rel="stylesheet" />
	@*<script src="~/Auth/js/pace.min.js"></script>*@
	<!--favicon-->
	<link rel="icon" href="~/Auth/images/favicon.ico" type="image/x-icon">
	<!-- Bootstrap core CSS-->
	<link href="~/Auth/css/bootstrap.min.css" rel="stylesheet" />
	<!-- animate CSS-->
	<link href="~/Auth/css/animate.css" rel="stylesheet" type="text/css" />
	<!-- Icons CSS-->
	<link href="~/Auth/css/icons.css" rel="stylesheet" type="text/css" />
	<!-- Custom Style-->
	<link href="~/Auth/css/app-style.css" rel="stylesheet" />

</head>

<body class="bg-theme bg-theme1">

	<!-- start loader -->
	<div id="pageloader-overlay" class="visible incoming"><div class="loader-wrapper-outer"><div class="loader-wrapper-inner"><div class="loader"></div></div></div></div>
	<!-- end loader -->
	<!-- Start wrapper-->
	<div id="wrapper">
		<!--Start Back To Top Button-->
		<a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
		<!--End Back To Top Button-->
		@RenderBody()
		<!--start color switcher-->
		<div class="right-sidebar">
			<div class="switcher-icon">
				<i class="zmdi zmdi-settings zmdi-hc-spin"></i>
			</div>
			<div class="right-sidebar-content">

				<p class="mb-0">Gaussion Texture</p>
				<hr>

				<ul class="switcher">
					<li id="theme1"></li>
					<li id="theme2"></li>
					<li id="theme3"></li>
					<li id="theme4"></li>
					<li id="theme5"></li>
					<li id="theme6"></li>
				</ul>

				<p class="mb-0">Gradient Background</p>
				<hr>

				<ul class="switcher">
					<li id="theme7"></li>
					<li id="theme8"></li>
					<li id="theme9"></li>
					<li id="theme10"></li>
					<li id="theme11"></li>
					<li id="theme12"></li>
					<li id="theme13"></li>
					<li id="theme14"></li>
					<li id="theme15"></li>
				</ul>

			</div>
		</div>
		<!--end color switcher-->

	</div><!--wrapper-->
	<!-- Bootstrap core JavaScript-->
	<script src="~/Auth/js/jquery.min.js"></script>
	<script src="~/Auth/js/popper.min.js"></script>
	<script src="~/Auth/js/bootstrap.min.js"></script>

	<!-- sidebar-menu js -->
	<script src="~/Auth/js/sidebar-menu.js"></script>

	<!-- Custom scripts -->
	<script src="~/Auth/js/app-script.js"></script>


	
	<script src="~/js/site.js" asp-append-version="true"></script>



	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebUI/Views/Shared/_NavBarLogin.cshtml
@using System.Security.Claims
@if (User.Identity.IsAuthenticated)
{
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">       
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        @User.Identity.Name
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        @if (User.HasClaim(x =>x.Type == ClaimTypes.Role && x.Value == "Admin"))
                            {
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Admin Panel</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Profile</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="PasswordChange">PasswordChange</a></li>
                            }
                            <li><a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="UserEdit">UserEdit</a></li>
                            <li><a class="dropdown-item" asp-controller="Auth" asp-action="Logout">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
}